from core.utils.clear_folder import clear_folder
from core.utils.set_random_seed import set_random_seed
from core.utils.point_iterator import get_stroke_point_iterator
from core.utils.distributed_context import distributed_context